# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e58f8cb8515087badb2a54e259bfa086db233bea684125505bd1e8d1fa8b2b95e810af2cc22e1afa9346296c39ca1a9c77473ca9b29445a99796f151ca943e6a

test:
  secret_key_base: 1bf4738ed523765708ea9dc53eba4229d765d1f21da103c732560a47be6b937f6798212824d8e008e58851712e52dc0190869dd744c6fb5b685d2f32aa7180c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
